# Generated by Django 3.0.5 on 2020-04-16 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('reference_date', models.DateField(default=datetime.date.today)),
                ('text', models.TextField()),
                ('tags', models.CharField(default='', max_length=500)),
                ('image', models.CharField(max_length=1000)),
                ('classification', models.IntegerField(default=0)),
            ],
        ),
    ]
